export default {
  ADD_INVENTORY: 'ADD_INVENTORY',
  BULK_ADD_INVENTORY: 'BULK_ADD_INVENTORY',
  CREATE_INVENTORY: 'CREATE_INVENTORY',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  DELETE_INVENTORY: 'DELETE_INVENTORY',
  EMPTY_CART: 'EMPTY_CART',
  HYDRATE_CART: 'HYDRATE_CART',
  HYDRATE_INVENTORY: 'HYDRATE_INVENTORY',
  LOAD_STORED_STATE: 'LOAD_STORED_STATE',
  RESET_CART: 'RESET_CART',
  UPDATE_CART: 'UPDATE_CART',
  UPDATE_FILTER: 'UPDATE_FILTER'
};
