export default {
  CREATE_INVENTORY: 'CREATE_INVENTORY',
  ADD_INVENTORY: 'ADD_INVENTORY',
  HYDRATE_INVENTORY: 'HYDRATE_INVENTORY',
  DELETE_INVENTORY: 'DELETE_INVENTORY',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_CART: 'DELETE_CART',
  HYDRATE_CART: 'HYDRATE_CART',
  LOAD_STORED_STATE: 'LOAD_STORED_STATE'
};
